export const sampleSnapshot = {
  trade_date: "2026-04-20",
  generated_at: "2026-04-20T11:14:12+09:00",
  sources: {
    ops_dir: "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20",
    daily_report_path:
      "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\daily_ops_report.json",
    daily_report_available: true,
    rehearsal_summary_path:
      "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\rehearsal_latest\\rehearsal_summary.json",
    rehearsal_available: true,
  },
  overview: {
    daily_report_available: true,
    status_level: "CRITICAL",
    health_outcome: "CRITICAL",
    highest_severity: "CRITICAL",
    report_outcome: "ATTENTION",
    artifact_count: 7,
    attention_flag_count: 4,
    critical_flag_count: 2,
    warning_flag_count: 2,
    action_required: true,
    top_action_codes: [
      "REVIEW_KILL_SWITCH",
      "REVIEW_SELL_EXECUTION_FAILURE",
      "REVIEW_EXECUTION_RECOVERY",
    ],
  },
  controls: {
    kill_switch_enabled: true,
    kill_switch_note: "manual emergency stop",
    kill_switch_updated_at: "2026-04-20T11:10:00+09:00",
    kill_switch_status_level: "CRITICAL",
  },
  scan: {
    live_preview: {
      available: true,
      status_level: "READY",
      highest_severity: "NONE",
      session_outcome: "COMPLETED",
      session_reason: null,
      preopen_readiness_outcome: "READY",
      preopen_readiness_reason: null,
      polling_started: true,
      polling_exit_code: 0,
      polling_stop_reason: "MAX_CYCLES_REACHED",
      timing2_setup_required: true,
      timing2_setup_ready: true,
      timing2_setup_signal_count: 12,
      attention_flags: [],
    },
    live_execute: {
      available: true,
      status_level: "WARNING",
      highest_severity: "WARNING",
      session_outcome: "POLLING_BLOCKED",
      session_reason: "MAX_DAILY_LOSS_REACHED",
      preopen_readiness_outcome: "READY",
      preopen_readiness_reason: null,
      polling_started: true,
      polling_exit_code: 4,
      polling_stop_reason: "MAX_DAILY_LOSS_REACHED",
      timing2_setup_required: true,
      timing2_setup_ready: true,
      timing2_setup_signal_count: 12,
      attention_flags: ["TRADING_SESSION_EXECUTE_BLOCKED"],
    },
    rehearsal_validation: {
      status_level: "READY",
      session_outcome: "COMPLETED",
      polling_stop_reason: "MAX_CYCLES_REACHED",
      timing2_setup_ready: true,
      timing2_30s_verified: true,
      attention_flags: [],
    },
  },
  executions: {
    buy_preview: {
      available: true,
      status_level: "READY",
      highest_severity: "NONE",
      stop_reason: null,
      blocked_count: 0,
      preview_ready_count: 2,
      submitted_count: 0,
      acted_count: 0,
      attention_flags: [],
    },
    buy_execute: {
      available: false,
      status_level: "MISSING",
      highest_severity: "NONE",
      stop_reason: null,
      blocked_count: null,
      preview_ready_count: null,
      submitted_count: null,
      acted_count: null,
      attention_flags: [],
    },
    sell_preview: {
      available: true,
      status_level: "READY",
      highest_severity: "NONE",
      stop_reason: null,
      blocked_count: 0,
      preview_ready_count: 1,
      submitted_count: 0,
      acted_count: 0,
      attention_flags: [],
    },
    sell_execute: {
      available: true,
      status_level: "CRITICAL",
      highest_severity: "CRITICAL",
      stop_reason: "BROKER_SELL_FAILED",
      blocked_count: 0,
      preview_ready_count: 0,
      submitted_count: 0,
      acted_count: 1,
      attention_flags: ["EXECUTE_SELL_SIGNALS_EXECUTE_FAILED"],
    },
  },
  recovery: {
    order_maintenance_preview: {
      available: true,
      status_level: "WARNING",
      highest_severity: "WARNING",
      manual_recovery_required_count: 2,
      attention_flags: ["MANUAL_RECOVERY_REQUIRED"],
    },
    order_maintenance_execute: {
      available: false,
      status_level: "MISSING",
      highest_severity: "NONE",
      manual_recovery_required_count: null,
      attention_flags: [],
    },
    execution_recovery_review: {
      available: true,
      status_level: "WARNING",
      highest_severity: "WARNING",
      manual_recovery_required_count: 2,
      attention_flags: ["EXECUTION_RECOVERY_REVIEW_HAS_MANUAL_ITEMS"],
    },
  },
  rehearsal: {
    available: true,
    path:
      "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\rehearsal_latest\\rehearsal_summary.json",
    status_level: "READY",
    overall_outcome: "COMPLETED",
    overall_reason: null,
    step_status_counts: {
      ok: 2,
      warning: 0,
      failed: 0,
    },
    trading_session: {
      status_level: "READY",
      session_outcome: "COMPLETED",
      polling_stop_reason: "MAX_CYCLES_REACHED",
      timing2_setup_ready: true,
      timing2_30s_verified: true,
      attention_flags: [],
    },
  },
  actions: {
    required: true,
    count: 3,
    top_action_codes: [
      "REVIEW_KILL_SWITCH",
      "REVIEW_SELL_EXECUTION_FAILURE",
      "REVIEW_EXECUTION_RECOVERY",
    ],
    items: [
      {
        action_code: "REVIEW_KILL_SWITCH",
        severity: "CRITICAL",
        summary:
          "Kill switch 상태와 note를 먼저 확인하고 자동 실행 재개를 보류하세요.",
        detail: "Kill switch is enabled. note=manual emergency stop",
        suggested_command:
          ".\\venv\\Scripts\\python.exe scripts\\set_kill_switch.py --output .\\data\\ops\\2026-04-20\\kill_switch.status.json",
      },
      {
        action_code: "REVIEW_SELL_EXECUTION_FAILURE",
        severity: "CRITICAL",
        summary:
          "직접 매도 실행 실패 원인을 확인하고 preview부터 다시 점검하세요.",
        detail: "BROKER_SELL_FAILED",
        suggested_command:
          ".\\venv\\Scripts\\python.exe scripts\\execute_sell_signals.py --trade-date 2026-04-20 --output .\\data\\ops\\2026-04-20\\execute_sell_signals.preview.json",
      },
      {
        action_code: "REVIEW_EXECUTION_RECOVERY",
        severity: "WARNING",
        summary: "수동 체결 복구 대상이 남아 있습니다.",
        detail: "Manual recovery required count=2",
        suggested_command:
          ".\\venv\\Scripts\\python.exe scripts\\run_execution_recovery_workflow.py --trade-date 2026-04-20 --output .\\data\\ops\\2026-04-20\\execution_recovery.review.json --draft-output .\\data\\ops\\2026-04-20\\execution_recovery.draft.json",
      },
    ],
  },
};
