export const sampleSnapshot = {
  trade_date: "2026-04-20",
  generated_at: "2026-04-20T11:14:12+09:00",
  sources: {
    ops_dir: "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20",
    daily_report_path:
      "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\daily_ops_report.json",
    daily_report_available: true,
    daily_ops_check_path:
      "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\daily_ops_check.json",
    daily_ops_check_available: true,
    buy_strategy_selection_path:
      "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\buy_strategy.selection.json",
    buy_strategy_selection_available: true,
    rehearsal_summary_path:
      "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\rehearsal_latest\\rehearsal_summary.json",
    rehearsal_available: true,
  },
  overview: {
    daily_report_available: true,
    status_level: "CRITICAL",
    health_outcome: "CRITICAL",
    highest_severity: "CRITICAL",
    report_outcome: "ATTENTION",
    artifact_count: 7,
    attention_flag_count: 4,
    critical_flag_count: 2,
    warning_flag_count: 2,
    action_required: true,
    top_action_codes: [
      "REVIEW_KILL_SWITCH",
      "REVIEW_SELL_EXECUTION_FAILURE",
      "REVIEW_EXECUTION_RECOVERY",
    ],
  },
  operator_summary: {
    available: true,
    source: "daily_ops_check",
    status_level: "WARNING",
    headline: "Startup blocked by open entry lot position mismatch.",
    detail:
      "Affected symbols: 005930 | Review executions and lot state before rerunning startup.",
    overall_outcome: "NOTIFICATION_REQUIRED",
    overall_reason: "Notification should be sent for startup mismatch.",
    health_outcome: "WARNING",
    should_notify: true,
    dispatch_outcome: "DISPATCHED",
    primary_attention_flag: "STARTUP_OPEN_ENTRY_LOT_POSITION_MISMATCH",
    primary_action_code: "REVIEW_OPEN_ENTRY_LOT_RECONCILE_BLOCK",
    startup_open_entry_lot_position_mismatch: true,
    affected_symbols: "005930",
  },
  startup: {
    available: true,
    status_level: "WARNING",
    highest_severity: "WARNING",
    outcome: "BLOCKED",
    reason: "Startup is blocked because reconcile found an open entry lot mismatch.",
    checked_at: "2026-04-20T08:59:00+09:00",
    universe_exists: true,
    universe_candidate_count: 25,
    reconcile_changed_rows: 1,
    unresolved_order_count: 0,
    live_position_count: 1,
    reconcile_reason_code: "OPEN_ENTRY_LOT_POSITION_MISMATCH",
    reconcile_reason_message:
      "Reconciliation would change positions for symbols that still have open entry lots. Review executions first: 005930",
    attention_flags: ["STARTUP_OPEN_ENTRY_LOT_POSITION_MISMATCH"],
  },
  controls: {
    kill_switch_enabled: true,
    kill_switch_note: "manual emergency stop",
    kill_switch_updated_at: "2026-04-20T11:10:00+09:00",
    kill_switch_status_level: "CRITICAL",
  },
  strategy: {
    selection_available: true,
    source: "selection_artifact",
    selection_path:
      "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\buy_strategy.selection.json",
    buy_strategy: "timing2",
    effective_buy_strategy: "timing2",
    run_timing1: false,
    run_timing2: true,
    updated_at: "2026-04-20T11:12:00+09:00",
    note: "focus on confirmed Timing2 revision",
    applies_to_next_run: true,
    status_level: "READY",
  },
  scan: {
    live_preview: {
      card_key: "scan-live-preview",
      available: true,
      status_level: "READY",
      highest_severity: "NONE",
      session_outcome: "COMPLETED",
      session_reason: null,
      preopen_readiness_outcome: "READY",
      preopen_readiness_reason: null,
      polling_started: true,
      polling_exit_code: 0,
      polling_stop_reason: "MAX_CYCLES_REACHED",
      timing2_setup_required: true,
      timing2_setup_ready: true,
      timing2_setup_signal_count: 12,
      attention_flags: [],
    },
    live_execute: {
      card_key: "scan-live-execute",
      available: true,
      status_level: "WARNING",
      highest_severity: "WARNING",
      session_outcome: "POLLING_BLOCKED",
      session_reason: "MAX_DAILY_LOSS_REACHED",
      preopen_readiness_outcome: "READY",
      preopen_readiness_reason: null,
      polling_started: true,
      polling_exit_code: 4,
      polling_stop_reason: "MAX_DAILY_LOSS_REACHED",
      timing2_setup_required: true,
      timing2_setup_ready: true,
      timing2_setup_signal_count: 12,
      attention_flags: ["TRADING_SESSION_EXECUTE_BLOCKED"],
    },
    rehearsal_validation: {
      card_key: "scan-rehearsal-validation",
      status_level: "READY",
      session_outcome: "COMPLETED",
      polling_stop_reason: "MAX_CYCLES_REACHED",
      timing2_setup_ready: true,
      timing2_30s_verified: true,
      attention_flags: [],
    },
  },
  executions: {
    buy_preview: {
      card_key: "execution-buy-preview",
      available: true,
      status_level: "READY",
      highest_severity: "NONE",
      stop_reason: null,
      blocked_count: 0,
      preview_ready_count: 2,
      submitted_count: 0,
      acted_count: 0,
      attention_flags: [],
    },
    buy_execute: {
      card_key: "execution-buy-execute",
      available: false,
      status_level: "MISSING",
      highest_severity: "NONE",
      stop_reason: null,
      blocked_count: null,
      preview_ready_count: null,
      submitted_count: null,
      acted_count: null,
      attention_flags: [],
    },
    sell_preview: {
      card_key: "execution-sell-preview",
      available: true,
      status_level: "READY",
      highest_severity: "NONE",
      stop_reason: null,
      blocked_count: 0,
      preview_ready_count: 1,
      submitted_count: 0,
      acted_count: 0,
      attention_flags: [],
    },
    sell_execute: {
      card_key: "execution-sell-execute",
      available: true,
      status_level: "CRITICAL",
      highest_severity: "CRITICAL",
      stop_reason: "BROKER_SELL_FAILED",
      blocked_count: 0,
      preview_ready_count: 0,
      submitted_count: 0,
      acted_count: 1,
      attention_flags: ["EXECUTE_SELL_SIGNALS_EXECUTE_FAILED"],
    },
  },
  recovery: {
    order_maintenance_preview: {
      card_key: "recovery-maintenance-preview",
      available: true,
      status_level: "WARNING",
      highest_severity: "WARNING",
      manual_recovery_required_count: 2,
      stale_signal_preview_ready_count: 3,
      stale_signal_cleaned_count: 0,
      stale_signal_blocked_count: 1,
      stale_signal_symbol_hint: "005930, 000660, 035420, 051910",
      stale_signal_blocked_reason_codes:
        "INVALID_SIGNAL_SCANNED_AT, SIGNAL_TIMESTAMP_IN_FUTURE, STALE_SIGNAL_AGE_EXCEEDED, UNKNOWN_REASON",
      attention_flags: [
        "MANUAL_RECOVERY_REQUIRED",
        "STALE_SIGNAL_CLEANUP_BLOCKED_ITEMS",
      ],
    },
    order_maintenance_execute: {
      card_key: "recovery-maintenance-execute",
      available: true,
      status_level: "READY",
      highest_severity: "NONE",
      manual_recovery_required_count: 0,
      stale_signal_preview_ready_count: 0,
      stale_signal_cleaned_count: 2,
      stale_signal_blocked_count: 0,
      stale_signal_symbol_hint: "005930, 000660, 035420, 051910",
      stale_signal_blocked_reason_codes: null,
      attention_flags: [],
    },
    stale_signal_cleanup_review: {
      card_key: "recovery-stale-signal-review",
      available: true,
      status_level: "WARNING",
      highest_severity: "WARNING",
      path:
        "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\stale_signal_cleanup.review.json",
      review_file_name: "stale_signal_cleanup.review.json",
      source_label: "order_maintenance.execute",
      source_path:
        "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\order_maintenance.execute.json",
      source_file_name: "order_maintenance.execute.json",
      review_item_count: 5,
      blocked_item_count: 2,
      preview_ready_item_count: 2,
      cleaned_item_count: 1,
      top_symbols: "005930, 000660, 035420, 051910",
      preview_items: [
        {
          scope: "buy",
          symbol: "005930",
          strategy_name: "buy_timing2_30s_morning_reclaim",
          scanned_at: "2026-04-20T09:07:01+09:00",
          outcome: "BLOCKED",
          reason_code: "INVALID_SIGNAL_SCANNED_AT",
          age_seconds: 421,
        },
        {
          scope: "sell",
          symbol: "000660",
          strategy_name: "sell_stop_loss",
          scanned_at: "2026-04-20T09:12:44+09:00",
          outcome: "PREVIEW_READY",
          reason_code: "STALE_SIGNAL_AGE_EXCEEDED",
          age_seconds: 366,
        },
        {
          scope: "sell",
          symbol: "035420",
          strategy_name: "sell_take_profit",
          scanned_at: "2026-04-20T09:03:05+09:00",
          outcome: "CLEANED",
          reason_code: "STALE_SIGNAL_AGE_EXCEEDED",
          age_seconds: 605,
        },
      ],
      attention_flags: ["STALE_SIGNAL_CLEANUP_BLOCKED_ITEMS"],
    },
    execution_recovery_review: {
      card_key: "recovery-execution-review",
      available: true,
      status_level: "WARNING",
      highest_severity: "WARNING",
      manual_recovery_required_count: 2,
      attention_flags: ["EXECUTION_RECOVERY_REVIEW_HAS_MANUAL_ITEMS"],
    },
  },
  rehearsal: {
    available: true,
    path:
      "C:\\python\\auto_trader_v2\\data\\ops\\2026-04-20\\rehearsal_latest\\rehearsal_summary.json",
    status_level: "READY",
    overall_outcome: "COMPLETED",
    overall_reason: null,
    step_status_counts: {
      ok: 2,
      warning: 0,
      failed: 0,
    },
    trading_session: {
      status_level: "READY",
      session_outcome: "COMPLETED",
      polling_stop_reason: "MAX_CYCLES_REACHED",
      timing2_setup_ready: true,
      timing2_30s_verified: true,
      attention_flags: [],
    },
  },
  actions: {
    required: true,
    count: 4,
    top_action_codes: [
      "REVIEW_KILL_SWITCH",
      "REVIEW_SELL_EXECUTION_FAILURE",
      "REVIEW_STALE_SIGNAL_CLEANUP",
      "REVIEW_EXECUTION_RECOVERY",
    ],
    items: [
      {
        action_code: "REVIEW_KILL_SWITCH",
        severity: "CRITICAL",
        summary:
          "Kill switch 상태와 note를 먼저 확인하고 자동 실행 재개를 보류하세요.",
        detail: "Kill switch is enabled. note=manual emergency stop",
        suggested_command:
          ".\\venv\\Scripts\\python.exe scripts\\set_kill_switch.py --output .\\data\\ops\\2026-04-20\\kill_switch.status.json",
      },
      {
        action_code: "REVIEW_SELL_EXECUTION_FAILURE",
        severity: "CRITICAL",
        summary:
          "직접 매도 실행 실패 원인을 확인하고 preview부터 다시 점검하세요.",
        detail: "BROKER_SELL_FAILED",
        suggested_command:
          ".\\venv\\Scripts\\python.exe scripts\\execute_sell_signals.py --trade-date 2026-04-20 --output .\\data\\ops\\2026-04-20\\execute_sell_signals.preview.json",
      },
      {
        action_code: "REVIEW_STALE_SIGNAL_CLEANUP",
        severity: "WARNING",
        summary:
          "Blocked stale signal cleanup 항목을 review JSON으로 다시 확인하세요.",
        detail: "Stale signal cleanup blocked count=1 symbols=005930, 000660",
        suggested_command:
          ".\\venv\\Scripts\\python.exe scripts\\show_stale_signal_cleanup_review.py --trade-date 2026-04-20 --output .\\data\\ops\\2026-04-20\\stale_signal_cleanup.review.json",
      },
      {
        action_code: "REVIEW_EXECUTION_RECOVERY",
        severity: "WARNING",
        summary: "수동 체결 복구 대상이 남아 있습니다.",
        detail: "Manual recovery required count=2",
        suggested_command:
          ".\\venv\\Scripts\\python.exe scripts\\run_execution_recovery_workflow.py --trade-date 2026-04-20 --output .\\data\\ops\\2026-04-20\\execution_recovery.review.json --draft-output .\\data\\ops\\2026-04-20\\execution_recovery.draft.json",
      },
    ],
  },
};
